name: Actualiser la Base de Données

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# --- LA CORRECTION EST ICI ---
# On donne explicitement le droit au robot de modifier les fichiers
permissions:
  contents: write
# -----------------------------

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      # On passe en v4 pour corriger le warning Node.js
      - name: 📥 Récupérer le code
        uses: actions/checkout@v4
        
      - name: ⚙️ Préparer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: 🤖 Lancer l'aspiration des joueurs
        run: node scraper.js
        
      - name: 💾 Sauvegarder et publier database.json
        run: |
          git config --global user.name "GitHub Action Robot"
          git config --global user.email "action@github.com"
          git add database.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-update database.json" && git push)
